/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starbright;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2024-09-03")
public enum SEASON implements org.apache.thrift.TEnum {
  SPRING(1),
  SUMMER(2);

  private final int value;

  private SEASON(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static SEASON findByValue(int value) { 
    switch (value) {
      case 1:
        return SPRING;
      case 2:
        return SUMMER;
      default:
        return null;
    }
  }
}
